# ansible/site.yml

---
- name: Test playbook
  hosts: localhost
  connection: local
  vars:
    app_environment: "lab"
  tasks:
    - name: Visa ett meddelande
      debug:
        msg: "Ansible kör från kontrollnoden!"
 
    - name: Visa en variabel
      debug:
        msg: "Miljö: {{ app_environment }}"